version: '3.8'

services:
  node:
    build:
      context: ""
      dockerfile: .docker/Dockerfile
    command: nodemon index.js
    environment:
      - NODE_ENV=development
    volumes:
      - ./:/app