name: Docker-Image-Publish
# On merge to the master branch, the workflow will be triggered.
on:
  push:
    branches:
      - master
jobs:
    publish:
        name: docker-publish-app
        runs-on: ubuntu-latest
        steps:
        - name: Checkout repository
          uses: actions/checkout@v4
        - name: Build Docker image
          run: docker build . --file .docker/Dockerfile -t ineptigenex:lastest
        - name: Login to Docker Hub
          run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
        # Push the Docker image to Docker Hub.
        - name: Push Docker image
          run: docker push ineptigenex:lastest
        # Auto versioning the Docker image.
        - name: Auto versioning Docker image
          run: docker tag ineptigenex:lastest ineptigenex:$(date +%s)